#!/usr/bin/perl
#


use Getopt::Std;


getopts('N:n:h');

if ($opt_h || !($opt_n || $opt_N)) {
  print <<EOF;
Usage: $0 -n <number of instances>
EOF
  exit;
}

if ($opt_N) {
  my $nodestr = sprintf "%02d",$opt_N;
  system("docker container exec r$nodestr sh -c 'vtysh < /etc/frr/solution-02b-multihomed'");
  exit;
}

for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  my $targetip = "10.99.1.1$nodestr";
  `(fortune | head -1;sleep 1) | nc -u $targetip 7`;
}

