#!/usr/bin/perl
#


use Getopt::Std;


getopts('N:n:h');

if ($opt_h || !($opt_n || $opt_N)) {
  print <<EOF;
Usage: $0 -n <number of instances>
EOF
  exit;
}

if ($opt_N) {
  my $nodestr = sprintf "%02d",$opt_N;
  my $targetip = "2001:db8:500:99::1$nodestr";
  `(/usr/games/fortune | head -1;sleep 1) | nc -w 1 -u $targetip 7`;
  exit;
}

for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  my $targetip = "2001:db8:500:99::1$nodestr";
  `(/usr/games/fortune | head -1;sleep 1) | nc -w 1 -u $targetip 7`;
}

