#!/usr/bin/perl
#
#
#


use Getopt::Std;


getopts('n:h');

if ($opt_h || !$opt_n) {
  print <<EOF;
Usage: $0 -n <number of instances>
EOF
  exit;
}

print <<EOF;
version: '2.4'
services:
  distributor:
    image: wtremmel/distributor
    hostname: distributor
    container_name: distributor
    ports:
      - "9000:80"
    volumes:
      - ./config/distributor:/etc/distributor
    networks:
      admin:
EOF

for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  print <<EOF;
  r$nodestr:
    image: wtremmel/wireshark:latest
    hostname: r$nodestr
    container_name: r$nodestr
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
    ports:
      - "90$nodestr:14500"
    networks:
      admin:
        priority: 1000
      testnet:
        priority: 100
        ipv4_address: 10.99.1.1$nodestr
        ipv6_address: 2001:db8:500:99::1$nodestr

EOF
}

print <<EOF;
networks:
  admin:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.1.1.0/24
        - subnet: 2001:db8:1::/64
  testnet:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.99.1.0/24
        - subnet: 2001:db8:500:99::/64
EOF
