version: '2.4'
services:
  distributor:
    image: wtremmel/distributor
    hostname: distributor
    container_name: distributor
    ports:
      - "9000:80"
    volumes:
      - ./config/distributor:/etc/distributor
    networks:
      admin:
  r01:
    image: wtremmel/wireshark:latest
    hostname: r01
    container_name: r01
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
    ports:
      - "9001:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config/r01:/config
    networks:
      admin:
        priority: 1000
      testnet:
        priority: 100
        ipv4_address: 10.99.1.101
        ipv6_address: 2001:db8:500:99::101

  r02:
    image: wtremmel/wireshark:latest
    hostname: r02
    container_name: r02
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
    ports:
      - "9002:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config/r02:/config
    networks:
      admin:
        priority: 1000
      testnet:
        priority: 100
        ipv4_address: 10.99.1.102
        ipv6_address: 2001:db8:500:99::102

networks:
  admin:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.1.1.0/24
        - subnet: 2001:db8:1::/64
  testnet:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.99.1.0/24
        - subnet: 2001:db8:500:99::/64
