#!/usr/bin/perl
#


use Getopt::Std;

getopts('N:n:ha');

if ($opt_h || !($opt_a || $opt_n || $opt_N)){
  print <<EOF;
Usage: $0 (-a | -n <number of instances> | -N <instance number> )
EOF
  exit;
}

if ($opt_a) {
  $opt_n = $ENV{Participants};
}


for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  my $targetip = "2001:db8:500:99::1$nodestr";

  $| = 1;
  open(F,"|nc -q 1 $targetip 7");
  my $text = `fortune`;
  print F $text;
  close F;
}

