#!/usr/bin/perl
#


use Getopt::Std;


getopts('N:n:h');

if ($opt_h || !($opt_n || $opt_N)) {
  print <<EOF;
Usage: $0 -n <number of instances>
EOF
  exit;
}


for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  my $targetip = "10.99.1.1$nodestr";

  $| = 1;
  open(F,"|nc -q 1 $targetip 7");
  my $text = `fortune`;
  print F $text;
  close F;
}

