#!/usr/bin/perl
#


use Getopt::Std;


getopts('N:n:h');

if ($opt_h || !($opt_n || $opt_N)) {
  print <<EOF;
Usage: $0 -n <number of instances>
EOF
  exit;
}

if ($opt_N) {
  my $nodestr = sprintf "%02d",$opt_N;
  `docker container exec -it r$nodestr traceroute -q 1 -6n www.de-cix.net`;
  exit;
}

for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  `docker container exec -it r$nodestr traceroute -q 1 -6n www.de-cix.net`;
}

