#!/usr/bin/perl
#


use Getopt::Std;

getopts('N:n:ha');

if ($opt_h || !($opt_a || $opt_n || $opt_N)){
  print <<EOF;
Usage: $0 (-a | -n <number of instances> | -N <instance number> )
EOF
  exit;
}

if ($opt_a) {
  $opt_n = $ENV{Participants};
}


if ($opt_N) {
  my $nodestr = sprintf "%02d",$opt_N;
  `docker container exec -it r$nodestr curl http://httpforever.com`;
  exit;
}

`ip6tables -t nat -A POSTROUTING -s 2001:db8:1::/64 -d ::/0 -j MASQUERADE`;

for ($i = 1; $i <= $opt_n; $i++) {
  my $nodestr = sprintf "%02d",$i;
  `docker container exec -it r$nodestr curl -6 http://httpforever.com`;
}

